### ISSUE TITLE
Cos Error Code: PhpInternalXmlParseError, Status Code: 400, Cos Request ID: , Cos Error Type: client, Cos Error Message: A non-XML response was receivedmessage: A non-XML response was received, line: 60,

### ISSUE THREAD

**Issue by Benny66** [tencentyun/cos-php-sdk-v5#336]
"[\n    'putObject error#1, detail: Cos Error Code: PhpInternalXmlParseError, Status Code: 400, Cos Request ID: , Cos Error Type: client, Cos Error Message: A non-XML response was receivedmessage: A non-XML response was received, line: 60, file: /app/vendor/qcloud/cos-sdk-v5/src/ExceptionMiddleware.php, trace: #0 /app/vendor/qcloud/cos-sdk-v5/src/ExceptionMiddleware.php(56): Qcloud\\\\Cos\\\\ExceptionMiddleware->createException()\n#1 /app/vendor/qcloud/cos-sdk-v5/src/ExceptionMiddleware.php(35): Qcloud\\\\Cos\\\\ExceptionMiddleware->handle()\n#2 /app/vendor/guzzlehttp/promises/src/Promise.php(209): Qcloud\\\\Cos\\\\ExceptionMiddleware->Qcloud\\\\Cos\\\\{closure}()\n#3 /app/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\\\Promise\\\\Promise::callHandler()\n#4 /app/vendor/guzzlehttp/promises/src/FulfilledPromise.php(48): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}()\n#5 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\\\\Promise\\\\FulfilledPromise::GuzzleHttp\\\\Promise\\\\{closure}()\n#6 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\\\\Promise\\\\TaskQueue->run()\n#7 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(185): GuzzleHttp\\\\Handler\\\\CurlMultiHandler->tick()\n#8 /app/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\\\\Handler\\\\CurlMultiHandler->execute()\n#9 /app/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\n#10 /app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\n#11 /app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitList()\n#12 /app/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\n#13 /app/vendor/guzzlehttp/promises/src/Coroutine.php(68): GuzzleHttp\\\\Promise\\\\Promise->wait()\n#14 /app/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\\\\Promise\\\\Coroutine->GuzzleHttp\\\\Promise\\\\{closure}()\n#15 /app/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\n#16 /app/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\n#17 /app/vendor/guzzlehttp/promises/src/Coroutine.php(100): GuzzleHttp\\\\Promise\\\\Promise->wait()\n#18 /app/vendor/guzzlehttp/command/src/ServiceClient.php(78): GuzzleHttp\\\\Promise\\\\Coroutine->wait()\n#19 /app/vendor/guzzlehttp/command/src/ServiceClient.php(157): GuzzleHttp\\\\Command\\\\ServiceClient->execute()\n#20 /app/vendor/qcloud/cos-sdk-v5/src/Client.php(398): GuzzleHttp\\\\Command\\\\ServiceClient->__call()\n#21 /app/biz/cos/CosHandler.php(89): Qcloud\\\\Cos\\\\Client->__call()\n#22 /app/commands/UploadController.php(64): app\\\\biz\\\\cos\\\\CosHandler->putObject()\n#23 /app/commands/BaseExecuteController.php(105): app\\\\commands\\\\UploadController->execute()\n#24 /app/commands/BaseExecuteController.php(36): app\\\\commands\\\\BaseExecuteController->consumeMessage()\n#25 [internal function]: app\\\\commands\\\\BaseExecuteController->actionIndex()\n#26 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()\n#27 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\\\\base\\\\InlineAction->runWithParams()\n#28 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\\\\base\\\\Controller->runAction()\n#29 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\\\\console\\\\Controller->runAction()\n#30 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\\\\base\\\\Module->runAction()\n#31 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\\\\console\\\\Application->runAction()\n#32 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\\\\console\\\\Application->handleRequest()\n#33 /app/yii(21): yii\\\\base\\\\Application->run()\n#34 {main}, ',\n]"

**Comment by Benny66** [comment]
这个错误码PhpInternalXmlParseError在文档中无法找到：https://cloud.tencent.com/document/product/436/7730

**Comment by Benny66** [comment]
经排查，上传的文件名称乱码导致的
